spring:
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:9999/
      label: develop
  config:
    import: optional:configserver:http://localhost:9999/
